rm -rf crystm01*
rm -rf minsurfo*
rm -rf crystm02*
rm -rf shallow_water1*
rm -rf wathen100*
rm -rf gridgena*
rm -rf wathen120*
#rm -rf crystm03*
rm -rf thermomech_TC*
rm -rf Dubcova2*
rm -rf thermomech_dM*
rm -rf qa8fm*